### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by yfzm** [se-kiwi/ds-lab#1]
- [x] 部署k8s
- [ ] 搭建spark集群
- [ ] 搭建hadoop集群
- [ ] 搭建kafka集群
- [ ] 搭建zookeeper集群
- [ ] 搭建mysql(单节点或集群)
- [ ] 实现HTTP data sender(可以考虑使用Python)
- [ ] 实现HTTP data receiver，将数据存入kafka
- [ ] spark streaming处理逻辑
- [x] 分布式锁与数据库访问接口
- [ ] 创建线程修改zookeeper中的货币信息
- [ ] 实现test data generator 
--------------
可改进：
- [ ] 启动时清空并初始化数据库，或留一个接口，便于测试

**Comment by laazy** [comment]
已经分成多个issue，并用kanban管理
